In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ApexPlanet_DataAnalytics_Dataset.xlsx to ApexPlanet_DataAnalytics_Dataset.xlsx

In [ ]:
df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

print(df.head())

    Order_ID  Order_Date Customer_ID Customer_Name   Age  Gender       City  \
0  ORD100002  2025-02-25    CUST5529  Customer_227  30.0  Female  Bengaluru
1  ORD100003  2025-10-14    CUST3127  Customer_182  63.0    Male  Bengaluru
2  ORD100004  2025-05-13    CUST8887  Customer_487  62.0  Female  Bengaluru
3  ORD100005  2025-12-02    CUST2515  Customer_470  65.0  Female    Kolkata
4  ORD100006  2025-11-20    CUST4796  Customer_380  44.0    Male  Bengaluru

  Product     Category  Quantity  Unit_Price  Total_Sales
0    Rice      Grocery         7     2829.77     19808.39
1    Book    Education         5    27906.16    139530.80
2    Book    Education         8    37491.06    299928.48
3  Mobile  Electronics         9    28541.36    256872.24
4    Rice      Grocery        10    14036.59    140365.90

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB
None

In [ ]:
print(df.shape)

(1000, 12)

In [ ]:
print(df.columns)

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age',
       'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price',
       'Total_Sales'],
      dtype='object')

In [ ]:
print(df.isnull().sum())

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
print(df.dtypes)

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [ ]:
print(df.describe())

              Age     Quantity    Unit_Price    Total_Sales
count  980.000000  1000.000000   1000.000000    1000.000000
mean    41.360204     5.435000  25486.783410  139399.439650
std     13.822597     2.838632  14179.402361  114100.051546
min     18.000000     1.000000    145.780000     437.340000
25%     30.000000     3.000000  13895.722500   47066.632500
50%     41.000000     5.000000  25398.740000  108594.025000
75%     54.000000     8.000000  37512.382500  203722.882500
max     65.000000    10.000000  49997.530000  493677.500000

In [ ]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

df["Order_Date"].head()

0   2025-02-25
1   2025-10-14
2   2025-05-13
3   2025-12-02
4   2025-11-20
Name: Order_Date, dtype: datetime64[ns]

In [ ]:
df["Month"] = df["Order_Date"].dt.month_name()

df[["Order_Date", "Month"]].head()

  Order_Date     Month
0 2025-02-25  February
1 2025-10-14   October
2 2025-05-13       May
3 2025-12-02  December
4 2025-11-20  November

In [ ]:
import numpy as np

In [ ]:
df["Sales_Category"] = np.where(
    df["Total_Sales"] > df["Total_Sales"].median(),
    "High",
    "Low"
)

df[["Total_Sales", "Sales_Category"]].head()

   Total_Sales Sales_Category
0     19808.39            Low
1    139530.80           High
2    299928.48           High
3    256872.24           High
4    140365.90           High

In [ ]:
df["Sales_Category"].value_counts()

Sales_Category
Low     500
High    500
Name: count, dtype: int64

In [ ]:
df.to_excel("Cleaned_Sales_Dataset.xlsx", index=False)

print("File saved successfully")

File saved successfully

In [ ]:
from google.colab import files

files.download("Cleaned_Sales_Dataset.xlsx")