In [1]:
# Upload your Excel file

from google.colab import files
uploaded = files.upload()

Saving Cleaned_Sales_Dataset (1).xlsx to Cleaned_Sales_Dataset (1).xlsx

In [2]:
#Import the required libraries
import pandas as pd
from scipy import stats

In [4]:
#Read your Excel dataset
df = pd.read_excel("Cleaned_Sales_Dataset (1).xlsx")

df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,Month,Sales_Category
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,February,Low
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,October,High
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,May,High
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,December,High
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,November,High

In [5]:
df['Gender'].value_counts()

Gender
Male      511
Female    489
Name: count, dtype: int64

Write your Hypothesis

Business Question:

Is there a significant difference in average Total Sales between Male and Female customers?

H₀ — Null Hypothesis:

There is no significant difference in average Total Sales between Male and Female customers.

H₁ — Alternative Hypothesis:

There is a significant difference in average Total Sales between Male and Female customers.

In [6]:
#Separate Male and Female Sales

male_sales = df[df['Gender'] == 'Male']['Total_Sales']

female_sales = df[df['Gender'] == 'Female']['Total_Sales']

In [7]:
#Perform the T-Test
t_statistic, p_value = stats.ttest_ind(
    male_sales,
    female_sales,
    equal_var=False
)

print("T-Statistic:", t_statistic)
print("P-Value:", p_value)

T-Statistic: 0.6826103913380815
P-Value: 0.4950114785145835

In [8]:
#Get the Average Sales
df.groupby('Gender')['Total_Sales'].mean()

Gender
Female    136883.208630
Male      141807.339785
Name: Total_Sales, dtype: float64